#!/usr/bin/env python
"""Regenerate JIS X 0208 data using the CPython standard-library euc_jp codec.

Build-time only; the Go decoder never executes Python. Row/cell bytes in
0x21..0x7e become EUC-JP by setting bit 7. Unassigned entries remain zero.
See README.md and THIRD_PARTY_NOTICES.md for provenance and licensing.
"""

import json
from pathlib import Path


def generate_jis() -> str:
    lines = [
        "// Code generated by generate_tables.py using CPython euc_jp; DO NOT EDIT.",
        "// JIS X 0208 mapping data. See THIRD_PARTY_NOTICES.md (PSF-2.0).",
        "package arib", "", "var jis0208 = [94 * 94]rune{",
    ]
    for row in range(0x21, 0x7F):
        for cell in range(0x21, 0x7F):
            try:
                text = bytes((row | 0x80, cell | 0x80)).decode("euc_jp")
            except UnicodeDecodeError:
                continue
            if len(text) != 1:
                raise ValueError(f"Unexpected multi-character mapping: {row:02x}{cell:02x}")
            index = (row - 0x21) * 94 + cell - 0x21
            lines.append(f"\t{index}: 0x{ord(text):04x}, // {row:02x}{cell:02x}")
    lines.append("}\n")
    return "\n".join(lines)


def generate_additional() -> str:
    source = json.loads(Path(__file__).with_name("additional_symbols.json").read_text(encoding="utf-8"))
    # Preserve the upstream per-file ISC notice in the generated mapping.
    notice = """// Copyright (C) 2021 magicxqq <xqq@xqq.im>. All rights reserved.
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
"""
    lines = [
        "// Code generated by generate_tables.py; DO NOT EDIT.",
        "// Additional mappings derived from libaribcaption; see THIRD_PARTY_NOTICES.md.",
        notice, "package arib", "", "var additionalSymbols = map[uint16]rune{",
    ]
    for code, text in sorted(source["mapping"].items()):
        if len(text) != 1:
            raise ValueError(f"Expected one Unicode character for {code}")
        lines.append(f"\t0x{code}: 0x{ord(text):x},")
    lines.append("}\n")
    return "\n".join(lines)


if __name__ == "__main__":
    output = Path(__file__).with_name("jis_table.go")
    output.write_text(generate_jis(), encoding="utf-8", newline="\n")
    print(f"Generated {output.name}")
    output = Path(__file__).with_name("additional_table.go")
    output.write_text(generate_additional(), encoding="utf-8", newline="\n")
    print(f"Generated {output.name}")
